# Configuration for C++ SDRTrunk Transcriber

# Directory to monitor for new MP3 files
DirectoryToMonitor: "/path/to/monitor"

# Number of seconds to wait before looping
LoopWaitSeconds: 5

# OpenAI API Key for transcription
OPENAI_API_KEY: "your_OPENAI_API_KEY_here"

XML_PATH: "/home/YOUR_USER/SDRTrunk/playlist/default.xml"
DATABASE_PATH: "/home/YOUR_USER/SDRTrunk/recordings.db"
TEN_SIGN_FILE: "/home/YOUR_USER/SDRTrunk/Some_Co_NC_TENSIGN.txt"
CALLSIGNS_PATH: "/home/YOUR_USER/SDRTrunk/callsigns.db"
NCSHP_TEN_SIGN_FILE: "/home/YOUR_USER/SDRTrunk/NCSHP_TENCODE.txt"
SIGNALS_FILE: "/home/YOUR_USER/SDRTrunk/NCSHP_SIGNALS.txt"
