# Configuration for C++ SDRTrunk Transcriber
# config.yaml

# Directory to monitor for new MP3 files
DirectoryToMonitor: "/path/to/monitor"

# Number of seconds to wait before looping
LoopWaitSeconds: 5

# OpenAI API Key for transcription
OPENAI_API_KEY: "your_OPENAI_API_KEY_here"

# sqlite3 database for saving file information and transcriptions
DATABASE_PATH: "/home/YOUR_USER/SDRTrunk/recordings.db"


# These are not used yet, but will be in the future in complicated-monitor-dir
XML_PATH: "/home/YOUR_USER/SDRTrunk/playlist/default.xml"
TEN_SIGN_FILE: "/home/YOUR_USER/SDRTrunk/Some_Co_NC_TENSIGN.txt"
CALLSIGNS_PATH: "/home/YOUR_USER/SDRTrunk/callsigns.db"
NCSHP_TEN_SIGN_FILE: "/home/YOUR_USER/SDRTrunk/NCSHP_TENCODE.txt"
SIGNALS_FILE: "/home/YOUR_USER/SDRTrunk/NCSHP_SIGNALS.txt"
