# Configuration for C++ SDRTrunk Transcriber

# OpenAI API Key for transcription
OPENAI_API_KEY: "YOUR_API_KEY"

# How frequently should we poll the DirectoryToMonitor for new files
# used in main.cpp
LoopWaitSeconds: 60

# Directory to monitor for new SDRTrunk P25 MP3 files
# used in main.cpp
DirectoryToMonitor: "/home/USER/SDRTrunk/recordings"

# sqlite3 database for saving file information and transcriptions
# we will be initializing this database
# schema in DatabaseManager
DATABASE_PATH: "/home/USER/SDRTrunk/recordings.db"

# Talkgroup-specific glossary mappings
# Want a tencode/callsign/signal/etc to have a translation appended to the end
# of the transcription? Add it here! See howToFormatYourJSON.json for expected format.
TALKGROUP_FILES:
  52197-52201:
    GLOSSARY:
      [
        "/home/USER/SDRTrunk/tencode_glossary.json",
        "/home/USER/SDRTrunk/signals_glossary.json",
      ]
  28513,41003-4,41013,41020:
    GLOSSARY: ["/home/USER/SDRTrunk/tencode_glossary.json"]

# Minimum duration in seconds for an MP3 file to be processed
# used in fileProcessor.cpp
MIN_DURATION_SECONDS: 9

# MAX_RETRIES: The maximum number of times the program will attempt to reprocess a file
# before giving up if it encounters errors or invalid responses.
# used in curlHelper.cpp
MAX_RETRIES: 3

# MAX_REQUESTS_PER_MINUTE: The maximum number of requests that can be sent to the API
# within RATE_LIMIT_WINDOW_SECONDS. This is to comply with the API's rate limiting policies.
# used in curlHelper.cpp
MAX_REQUESTS_PER_MINUTE: 50

# ERROR_WINDOW_SECONDS: The time window in seconds for tracking API errors.
# If the number of errors exceeds a 25% threshold within this window,
# the program will exit.
# used in curlHelper.cpp
ERROR_WINDOW_SECONDS: 300

# RATE_LIMIT_WINDOW_SECONDS: The time window in seconds for enforcing the rate limit.
# The program tracks the number of requests made in this period and ensures
# it doesn't exceed the maximum allowed requests per minute.
# used in curlHelper.cpp
RATE_LIMIT_WINDOW_SECONDS: 60

# TODO #3
# utilize the SDRTrunk playlist XML to convert:
# talkgroup ID to names
# radio ID to names
XML_PATH: "/home/USER/SDRTrunk/playlist/default.xml"

#############
# DEBUGGING #
#############
# If you want to see verbose output for a specific component, set it to true here.
# Warning: This will generate a lot of output!
DEBUG_CURL_HELPER: false
DEBUG_DATABASE_MANAGER: false
DEBUG_FILE_PROCESSOR: false
DEBUG_MAIN: false
DEBUG_TRANSCRIPTION_PROCESSOR: false
