# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: CMake Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Clone yaml-cpp
        run: git clone https://github.com/jbeder/yaml-cpp.git external/yaml-cpp

      - name: Clone CLI11
        run: git clone https://github.com/CLIUtils/CLI11.git external/CLI11

      - name: Set up vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: '${{ github.workspace }}/vcpkg'
          vcpkgGitCommitId: '8eb57355a4ffb410a2e94c07b4dca2dffbee8e50'

      - name: Install dependencies
        run: .\vcpkg\vcpkg install libsndfile libmpg123 curl:x64-windows sqlite3:x64-windows yaml-cpp:x64-windows nlohmann-json:x64-windows
        shell: cmd

      - name: Cache vcpkg packages
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/vcpkg/installed
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}
          restore-keys: |
            ${{ runner.os }}-vcpkg-

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -S . -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
